// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9kABgfLSnrLxnMlaNMHIR89lCAyO_Y3E',
    appId: '1:219227782156:android:ae6b63b435f9304c364229',
    messagingSenderId: '219227782156',
    projectId: 'ncec-74eb6',
    databaseURL: 'https://ncec-74eb6-default-rtdb.firebaseio.com',
    storageBucket: 'ncec-74eb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfeubBJhKCJI_s6BdXsWJTDRc1-FknDqM',
    appId: '1:219227782156:ios:2a4846cec3f19b5f364229',
    messagingSenderId: '219227782156',
    projectId: 'ncec-74eb6',
    databaseURL: 'https://ncec-74eb6-default-rtdb.firebaseio.com',
    storageBucket: 'ncec-74eb6.appspot.com',
    iosClientId: '219227782156-6ms8g41p4vhb3m1bemrur5jff7p280nj.apps.googleusercontent.com',
    iosBundleId: 'com.rayen.shababncec',
  );
}
